name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: vscode
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Run test
        run: bundle exec rake