name: CI

on:
  push:
    branches: [ master ]
    paths: &target_paths
      - 'src/**'
      - 'public/**'
      - 'test/**'
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - config.ru
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'test/**'
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - config.ru

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: vscode
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Run test
        run: bundle exec rake